import { Router } from 'express';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import dogRoutes from './dog.routes';
import eventRoutes from './event.routes';
import paymentRoutes from './payment.routes';
import uploadRoutes from './upload.routes';
// import certificateRoutes from './certificate.routes';
import groupRoutes from './group.routes';
import breedRoutes from './breed.routes';
import judgeRoutes from './judge.routes';
import settingsRoutes from './settings.routes';
import dashboardRoutes from './dashboard.routes';
import reportsRoutes from './report.routes';
import notificationsRoutes from './notifications.routes';
import supportRoutes from './support.routes';
import fCIGroupRoutes from './fCIGroup.routes';
import ageClassRoutes from './ageClass.routes';
import roleRoutes from './role.routes';
import permissionRoutes from './permission.routes';
import auditLogRoutes from './auditLog.routes';
import ownerRoutes from './owner.routes';
import breederRoutes from './breeder.routes';
import blogRoutes from './blog.routes';
import refundRoutes from './refund.routes';
import winnerTagRoutes from './winnerTag.routes';
import winnerRoutes from './winner.routes';
import mediaGalleryRoutes from './mediaGallery.routes';
import galleryRoutes from './gallery.routes';
import fAQRoutes from './fAQ.routes';
import homepageBannerRoutes from './homepageBanner.routes';
import pageBannerRoutes from './pageBanner.routes';
import cmsRoutes from './cms.routes';
import menuRoutes from './menu.routes';
import sponsorRoutes from './sponsor.routes';
import testimonialRoutes from './testimonial.routes';
import clubRoutes from './club.routes';

import { getHomeCms } from '../controllers/cms.controller';

const router = Router();

// Publicly accessible endpoints (prefix: /api/v1/public)
const publicRouter = Router();
publicRouter.use('/cms', cmsRoutes);
publicRouter.use('/menus', menuRoutes);
publicRouter.use('/homepage-banners', homepageBannerRoutes);
publicRouter.use('/banners', homepageBannerRoutes);
publicRouter.use('/page-banners', pageBannerRoutes);
publicRouter.use('/dogs', dogRoutes);
publicRouter.use('/events', eventRoutes);
publicRouter.use('/clubs', clubRoutes);
publicRouter.use('/judges', judgeRoutes);
publicRouter.use('/winners', winnerRoutes);
publicRouter.use('/gallery', galleryRoutes);
publicRouter.use('/sponsors', sponsorRoutes);
publicRouter.use('/testimonials', testimonialRoutes);
publicRouter.use('/fci-groups', fCIGroupRoutes);
publicRouter.use('/groups', fCIGroupRoutes);
publicRouter.use('/breeds', breedRoutes);
publicRouter.use('/blogs', blogRoutes);
publicRouter.use('/media', mediaGalleryRoutes);
publicRouter.use('/winner-tags', winnerTagRoutes);
publicRouter.get('/stats', getHomeCms);

router.use('/public', publicRouter);

// Existing routes (for dashboard/admin and compatibility)
router.use('/cms', cmsRoutes);
router.use('/menus', menuRoutes);
router.use('/homepage-banners', homepageBannerRoutes);
router.use('/page-banners', pageBannerRoutes);

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/dogs', dogRoutes);
router.use('/events', eventRoutes);
router.use('/payments', paymentRoutes);
router.use('/uploads', uploadRoutes);
// router.use('/certificates', certificateRoutes);
router.use('/groups', fCIGroupRoutes);
router.use('/fci-groups', fCIGroupRoutes);
router.use('/breeds', breedRoutes);
router.use('/judges', judgeRoutes);
router.use('/age-classes', ageClassRoutes);
router.use('/roles', roleRoutes);
router.use('/permissions', permissionRoutes);
router.use('/audit-logs', auditLogRoutes);
router.use('/owners', ownerRoutes);
router.use('/breeders', breederRoutes);
router.use('/blogs', blogRoutes);
router.use('/refunds', refundRoutes);
router.use('/winner-tags', winnerTagRoutes);
router.use('/winners', winnerRoutes);
router.use('/media', mediaGalleryRoutes);
router.use('/gallery', galleryRoutes);
router.use('/sponsors', sponsorRoutes);
router.use('/testimonials', testimonialRoutes);
router.use('/clubs', clubRoutes);
router.use('/cms/faqs', fAQRoutes);
router.use('/settings', settingsRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/reports', reportsRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/support', supportRoutes);

export { publicRouter };
export default router;
