-- ROLLBACK SCRIPT (MYSQL)
-- DANGER: This will wipe the entire MySQL schema.

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `User`;
DROP TABLE IF EXISTS `Role`;
DROP TABLE IF EXISTS `Permission`;
DROP TABLE IF EXISTS `UserRole`;
DROP TABLE IF EXISTS `RolePermission`;
DROP TABLE IF EXISTS `FCIGroup`;
DROP TABLE IF EXISTS `Breed`;
DROP TABLE IF EXISTS `Breeder`;
DROP TABLE IF EXISTS `Owner`;
DROP TABLE IF EXISTS `Dog`;
DROP TABLE IF EXISTS `DogPhoto`;
DROP TABLE IF EXISTS `DogDocument`;
DROP TABLE IF EXISTS `KCICertificate`;
DROP TABLE IF EXISTS `Club`;
DROP TABLE IF EXISTS `Event`;
DROP TABLE IF EXISTS `EventFCIGroup`;
DROP TABLE IF EXISTS `EventCategory`;
DROP TABLE IF EXISTS `Judge`;
DROP TABLE IF EXISTS `JudgeAssignment`;
DROP TABLE IF EXISTS `EventRegistration`;
DROP TABLE IF EXISTS `CompetitionRound`;
DROP TABLE IF EXISTS `CompetitionMatch`;
DROP TABLE IF EXISTS `Winner`;
DROP TABLE IF EXISTS `WinnerTag`;
DROP TABLE IF EXISTS `Payment`;
DROP TABLE IF EXISTS `PaymentLog`;
DROP TABLE IF EXISTS `Refund`;
DROP TABLE IF EXISTS `Notification`;
DROP TABLE IF EXISTS `NotificationTemplate`;
DROP TABLE IF EXISTS `NotificationLog`;
DROP TABLE IF EXISTS `MediaGallery`;
DROP TABLE IF EXISTS `EventGallery`;
DROP TABLE IF EXISTS `AuditLog`;
DROP TABLE IF EXISTS `ActivityLog`;
DROP TABLE IF EXISTS `Setting`;
DROP TABLE IF EXISTS `SerialGenerator`;
DROP TABLE IF EXISTS `DashboardMetric`;
DROP TABLE IF EXISTS `FAQ`;
DROP TABLE IF EXISTS `Testimonial`;
DROP TABLE IF EXISTS `Sponsor`;
DROP TABLE IF EXISTS `Banner`;
DROP TABLE IF EXISTS `Report`;
DROP TABLE IF EXISTS `CmsHeader`;
DROP TABLE IF EXISTS `CmsFooter`;
DROP TABLE IF EXISTS `CmsAbout`;

SET FOREIGN_KEY_CHECKS = 1;
